name: Pull Repos and Install Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pull-and-install:
    runs-on: windows-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Checkout Local LLM
        uses: actions/checkout@v3
        with:
          repository: ClinicianFOCUS/local-llm-container
          path: local-llm-container

      - name: Checkout The Speech2Text Container
        uses: actions/checkout@v3
        with:
          repository: ClinicianFOCUS/speech2text-container
          path: speech2text-container

      - name: Install release FreeScribe client installer from latest release
        run: |
          @echo off & mkdir freescribe & for /f "tokens=*" %i in ('curl -s https://api.github.com/repos/clinicianfocus/freescribe/releases/latest ^| findstr /i "browser_download_url.*windows.exe"') do @set "url=%i" & set "url=!url:*: =!" & set "url=!url:"=!" & powershell -Command "Invoke-WebRequest -Uri '!url!' -OutFile 'freescribe\downloaded_file.exe'"

      - name: Set up NSIS
        uses: joncloud/makensis-action@1c9f4bf2ea0c771147db31a2f3a7f5d8705c0105 # v4.1 commit hash
