name: Pull Repos and Install Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pull-and-install:
    runs-on: windows-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Checkout Local LLM
        uses: actions/checkout@v3
        with:
          repository: ClinicianFOCUS/local-llm-container
          path: local-llm-container

      - name: Checkout The Speech2Text Container
        uses: actions/checkout@v3
        with:
          repository: ClinicianFOCUS/speech2text-container
          path: speech2text-container

      - name: Get latest release
        id: get_release
        uses: actions/github-script@v6
        with:
          script: |
            const { data: release } = await github.rest.repos.getLatestRelease({
              owner: 'OWNER',   // Replace with the repository owner's username
              repo: 'REPO'      // Replace with the repository name
            });
            const asset = release.assets.find(asset => asset.name.endsWith('.exe'));
            if (!asset) {
              throw new Error('No executable found in the latest release assets.');
            }
            return asset.url;

      - name: Download latest release EXE
        run: |
          curl -L -H "Accept: application/octet-stream" -o FreeScribeInstaller_windows.exe ${{ steps.get_release.outputs.result }}

      - name: Set up NSIS
        uses: joncloud/makensis-action@1c9f4bf2ea0c771147db31a2f3a7f5d8705c0105 # v4.1 commit hash
